{% set version = "0.1.67" %}
{% set name = "jaxlib" %}

# compute right wheel filename for later
{% set pyver = "cp{}{}".format(PY_VER[0], PY_VER[2]) %}
{% set platform = "manylinux2010_x86_64" %}  # [linux]
{% set platform = "macosx_10_9_x86_64" %}  # [osx]
# {distribution}-{version}(-{build tag})?-{python tag}-{abi tag}-{platform tag}.whl.
{% set fn = "{}-{}-{}-none-{}.whl".format(name, version, pyver, platform) %}

# only use these for the URLS to help the bot
# the urls below have to be explicit for the bot to work
{% set linux_whl = "manylinux2010_x86_64" %}
{% set osx_whl = "macosx_10_9_x86_64" %}

package:
  name: jaxlib
  version: {{ version }}

source:
  fn: wheel.whl

  url: https://pypi.io/packages/cp36/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}-cp36-none-{{ linux_whl }}.whl  # [linux and py==36]
  sha256: 0f83f307f3d5864a05dca7a70a667c4c7e7de3cdd5c116b1ec78fc18b6da57cc  # [linux and py==36]
  url: https://pypi.io/packages/cp36/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}-cp36-none-{{ osx_whl }}.whl  # [osx and py==36]
  sha256: 13420851cb5245ed59f355d2b3f058f4725a421f7f4459e15eed549eafc16064  # [osx and py==36]

  url: https://pypi.io/packages/cp37/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}-cp37-none-{{ linux_whl }}.whl  # [linux and py==37]
  sha256: 35db3764e6d897ebf4206f904a7febfa2a867e824e219d5e9b16da07192e2ace  # [linux and py==37]
  url: https://pypi.io/packages/cp37/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}-cp37-none-{{ osx_whl }}.whl  # [osx and py==37]
  sha256: 84b2d19d36d6b55e4a8a22a8be7e8e3b67592e808d181485b04f0ce9b27bd2a1  # [osx and py==37]

  url: https://pypi.io/packages/cp38/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}-cp38-none-{{ linux_whl }}.whl  # [linux and py==38]
  sha256: 961d058fd2e63b093f732575272fa4bcb1a933806a1b03faf7e340e9462fa680  # [linux and py==38]
  url: https://pypi.io/packages/cp38/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}-cp38-none-{{ osx_whl }}.whl  # [osx and py==38]
  sha256: 94317ffc3df58a27917232119e9103badc90140a40335cebda20a58d8952e76b  # [osx and py==38]

  url: https://pypi.io/packages/cp39/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}-cp39-none-{{ linux_whl }}.whl  # [linux and py==39]
  sha256: aef419f9fb7a02c5892ac0c3f8883fbca6cef480f6836b557943e9b75763d811  # [linux and py==39]
  url: https://pypi.io/packages/cp39/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}-cp39-none-{{ osx_whl }}.whl  # [osx and py==39]
  sha256: fa38b0a5824c230b77f7cd5322e85a59f7822d80b76d751b5c8df4e179e5a701  # [osx and py==39]

build:
  number: 0
  skip: true  # [win or py2k]
  script:
    - mv wheel.whl {{ fn }}
    - {{ PYTHON }} -m pip install --no-deps -vv {{ fn }}

requirements:
  host:
    - python
    - pip
  run:
    - python
    - absl-py
    - numpy >=1.16
    - scipy
    - six
    - python-flatbuffers

test:
  requires:
    - pip
  commands:
    - pip check
  # imports:
    # cannot run the test b/c this is not really manylinux1 GLIBC_2.14
    # Google :-/
    # - jaxlib

about:
  home: http://github.com/google/jax
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Composable transformations of Python+NumPy programs: differentiate, vectorize, JIT to GPU/TPU, and more'

  dev_url: http://github.com/google/jax

extra:
  recipe-maintainers:
    - ericmjl
